In [2]:
import numpy as np

In [3]:
def matrix10_15(n):
    A=np.zeros([n,n])
    for i in range(n,0,-1):
        for j in range(0,i):
            A[j,j+(n-i)]=n-j-(n-i)
    for i in range(0,n-1):
        A[i+1,i]=n-i-1
    return A

def Aperturbation(n):
    Aperturb=np.zeros([n,n])
    Aperturb[0,n-2]=1e-08
    return Aperturb

In [10]:
E1_5,EV1_5=np.linalg.eig(matrix10_15(5))
E1_10,EV1_10=np.linalg.eig(matrix10_15(10))
E1_15,EV1_15=np.linalg.eig(matrix10_15(15))
E1_20,EV1_20=np.linalg.eig(matrix10_15(20))

E2_5,EV2_5=np.linalg.eig(matrix10_15(5)+Aperturbation(5))
E2_10,EV2_10=np.linalg.eig(matrix10_15(10)+Aperturbation(10))
E2_15,EV2_15=np.linalg.eig(matrix10_15(15)+Aperturbation(15))
E2_20,EV2_20=np.linalg.eig(matrix10_15(20)+Aperturbation(20))

print(E1_5-E2_5)
print(E1_10-E2_10)
print(E1_15-E2_15)
print(E1_20-E2_20)



[-3.78488352e-10  3.25754490e-09 -4.44089210e-16  3.83258041e-08
 -4.12048672e-08]
[-1.13686838e-13  7.42872430e-12 -2.77506018e-10  7.12682224e-09
 -9.81218371e-08 -2.83082257e-06 -6.40407038e-04  1.14623121e-03
 -5.99480700e-04  9.65786195e-05]
[-1.42108547e-13+0.j         -1.42108547e-14+0.j
 -1.77635684e-13+0.j          1.20934374e-11+0.j
 -6.95381530e-10+0.j          4.20443289e-08+0.j
 -2.54220192e-06+0.j         -3.69621000e-11+0.j
  5.75788336e-01+0.j          5.55256043e-02-0.1603061j
  6.67175408e-02+0.1603061j  -1.27104982e-01-0.19808562j
 -9.96249652e-02+0.19808562j -2.86350465e-01-0.03951654j
 -1.84948567e-01+0.03951654j]
[ 4.97379915e-14+0.j          8.52651283e-14+0.j
  3.55271368e-14+0.j          4.61852778e-14+0.j
 -4.26325641e-13+0.j          3.56710217e-11+0.j
 -3.29027472e-09+0.j          3.84417023e-07+0.j
 -5.86698658e-05+0.j          1.88972320e+00-0.18625088j
  1.18542986e+00+0.18625088j  2.25884616e-01-0.50146226j
  2.51689480e-01+0.55883983j -1.41350206e+00-0.

In [7]:
num1=np.linalg.norm(E1_5-E2_5)
num2=np.linalg.norm(E1_10-E2_10)
num3=np.linalg.norm(E1_15-E2_15)
num4=np.linalg.norm(E1_20-E2_20)

print("The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=5 is",num1)
print("The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=10 is",num2)
print("The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=15 is",num3)
print("The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=20 is",num4)
print("The n that has maximum norm is 20")

The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=5 is 5.6368991472282576e-08
The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=10 is 0.0014466097318101545
The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=15 is 0.7838015903718134
The norm of the difference between the eigenvalues of the original matrix and the perturbed matrix for n=20 is 3.1550087673404565
The n that has maximum norm is 20


### (c) np.eig(A) orders eigenvalue in largest to smallest order. Since we can observe that the perturbed value of eigenvalue gets larger when heading toward the lower part of eigen error matrix, this means that smaller eigenvalue is perturbed more than larger eigenvalues.

In [5]:
def eigcond(A):
    m,n=A.shape
    if m!=n:print("A is not a square matrix");return
    E,V=np.linalg.eig(A)
    lambda_diag=np.diag(E)
    c=np.zeros([n,1])
    invXt=np.linalg.inv(V).T
    for i in range(0,n):
        x=V[:,i]/np.linalg.norm(V[:,i])
        y=invXt[:,i]/np.linalg.norm(invXt[:,i])
        c[i,0]=1/np.abs(y.T@x)
    return c, lambda_diag
    

In [6]:
C5, diag5=eigcond(matrix10_15(5))
C10, diag10=eigcond(matrix10_15(10))
C15, diag15=eigcond(matrix10_15(15))
C20, diag20=eigcond(matrix10_15(20))

print(C5)
print(C10)
print(C15)
print(C20)

[[ 1.17104069]
 [ 1.24759337]
 [ 2.74954542]
 [ 9.51112611]
 [11.04051213]]
[[2.33925249e+00]
 [3.03028345e+00]
 [1.82869851e+00]
 [2.28708447e+00]
 [3.19198845e+01]
 [1.18367622e+03]
 [1.40819238e+05]
 [2.58974746e+05]
 [1.41030392e+05]
 [2.40275801e+04]]
[[5.64203242e+00]
 [1.06673451e+01]
 [8.13693122e+00]
 [3.62216652e+00]
 [2.03727027e+00]
 [1.37955165e+01]
 [5.80690317e+02]
 [6.86411257e+04]
 [8.92400280e+06]
 [5.49714271e+10]
 [1.43103765e+11]
 [1.30106597e+11]
 [4.94371975e+10]
 [7.92108056e+09]
 [4.67001263e+08]]
[[1.44225035e+01]
 [3.84825665e+01]
 [3.88415474e+01]
 [2.32219332e+01]
 [8.51938715e+00]
 [3.13689019e+00]
 [6.63062789e+00]
 [1.51162202e+02]
 [1.27150734e+04]
 [3.19628747e+06]
 [1.36746908e+09]
 [2.19283905e+13]
 [2.39651109e+13]
 [2.39651184e+13]
 [2.91368997e+13]
 [2.91369121e+13]
 [3.73426564e+13]
 [3.73426815e+13]
 [1.87157924e+13]
 [3.89054358e+11]]


## As the conditional number gets bigger when heading downwards, we can deduce that smaller eigenvalue has bigger conditional number, which matches the observation in (c).