In [1]:
import numpy as np
import scipy.linalg as la
from sympy import Matrix,pprint

In [2]:
A=np.array([[1,0,1],[-1,1,1],[-1,-1,1]])
P,L,U=la.lu(A)
print("P=\n",P)
print("L=\n",L)
print("U=\n",U)

P=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L=
 [[ 1.  0.  0.]
 [-1.  1.  0.]
 [-1. -1.  1.]]
U=
 [[1. 0. 1.]
 [0. 1. 2.]
 [0. 0. 4.]]


In [3]:
b1=np.array([1,1,1])
temp=np.linalg.inv(L)@b1
x=np.linalg.inv(U)@temp
print("x=\n",x)

x=
 [0. 0. 1.]


In [7]:
B=Matrix([[1,1/2,1/3],[1/2,1/3,1/4],[1/3,1/4,1/5]])
b2=Matrix([1,1,1])
L,U,P=B.LUdecomposition()
temp=L.inv()*b2
x=U.inv()*temp
print('L=');pprint(L)
print('U=');pprint(U)
print('P=');pprint(P)
print('x=');pprint(x)

L=
⎡        1           0   0⎤
⎢                         ⎥
⎢       0.5          1   0⎥
⎢                         ⎥
⎣0.333333333333333  1.0  1⎦
U=
⎡1         0.5           0.333333333333333 ⎤
⎢                                          ⎥
⎢0  0.0833333333333333  0.0833333333333333 ⎥
⎢                                          ⎥
⎣0          0           0.00555555555555552⎦
P=
[]
x=
⎡3.00000000000003 ⎤
⎢                 ⎥
⎢-24.0000000000002⎥
⎢                 ⎥
⎣30.0000000000002 ⎦
