In [1]:
import numpy as np
import scipy as sp

In [2]:
A1=np.array([[2,5,-1,-7],[-4,1,5,0]])
A2=np.array([[-1,1,2,3,5],[1,2,3,4,5],[-4,-3,-2,-1,0]])
U1,S1,V1t=sp.linalg.svd(A1)
U2,S2,V2t=sp.linalg.svd(A2)

In [3]:
print('For the case of (a)')
print('U=\n',U1);print('S=\n',np.diag(S1));print('V=\n',V1t.T)
r1=np.linalg.matrix_rank(A1)
print('basis is displaced in column vector of displayed matrices of each cases.')
print('basis of null space of A is\n',V1t[r1:4,:].T)
print('basis of range of A is \n',U1[:,0:r1])
print('basis of row space of A is \n',V1t[0:r1,:].T)
print('basis of null space of At is \n',U1[:,r1:2])

For the case of (a)
U=
 [[ 0.97924896  0.202661  ]
 [-0.202661    0.97924896]]
S=
 [[8.98084876 0.        ]
 [0.         6.35172068]]
V=
 [[ 0.30833855 -0.55286969  0.65571251  0.41146513]
 [ 0.5226214   0.31370302 -0.40783375  0.67980064]
 [-0.221867    0.73894682  0.60613676  0.19321197]
 [-0.76326223 -0.22334531 -0.19055436  0.57553164]]
basis is displaced in column vector of displayed matrices of each cases.
basis of null space of A is
 [[ 0.65571251  0.41146513]
 [-0.40783375  0.67980064]
 [ 0.60613676  0.19321197]
 [-0.19055436  0.57553164]]
basis of range of A is 
 [[ 0.97924896  0.202661  ]
 [-0.202661    0.97924896]]
basis of row space of A is 
 [[ 0.30833855 -0.55286969]
 [ 0.5226214   0.31370302]
 [-0.221867    0.73894682]
 [-0.76326223 -0.22334531]]
basis of null space of At is 
 []


In [4]:
print('For the case of (b)')
print('U=\n',U2);print('S=\n',np.diag(S2));print('V=\n',V2t.T)
r2=np.linalg.matrix_rank(A2)
print('basis is displaced in column vector of displayed matrices of each cases.')
print('basis of null space of A is\n',V2t[r2:5,:].T)
print('basis of range of A is \n',U2[:,0:r2])
print('basis of row space of A is \n',V2t[0:r2,:].T)
print('basis of null space of At is \n',U2[:,r2:3])

For the case of (b)
U=
 [[ 0.60141357  0.41142679 -0.68485744]
 [ 0.75004194  0.00452581  0.66137479]
 [-0.27520684  0.91143157  0.30586546]]
S=
 [[9.8802528  0.         0.        ]
 [0.         5.21461835 0.        ]
 [0.         0.         0.43400468]]
V=
 [[ 0.1264599  -0.77716661  0.28287798  0.03052831  0.54687112]
 [ 0.29625942 -0.44371729 -0.6444729   0.38726146 -0.3873352 ]
 [ 0.40518869 -0.1891667   0.00617171 -0.83557954 -0.31907184]
 [ 0.51411795  0.06538389  0.65681632  0.38726146 -0.3873352 ]
 [ 0.68391748  0.39883322 -0.27053457  0.03052831  0.54687112]]
basis is displaced in column vector of displayed matrices of each cases.
basis of null space of A is
 [[ 0.03052831  0.54687112]
 [ 0.38726146 -0.3873352 ]
 [-0.83557954 -0.31907184]
 [ 0.38726146 -0.3873352 ]
 [ 0.03052831  0.54687112]]
basis of range of A is 
 [[ 0.60141357  0.41142679 -0.68485744]
 [ 0.75004194  0.00452581  0.66137479]
 [-0.27520684  0.91143157  0.30586546]]
basis of row space of A is 
 [[ 0.1264599  -