In [1]:
import numpy as np
import scipy as sp

In [2]:
A1=np.array([[1,-1,0],[8,4,1],[-9,0,3]])
A2=np.array([[1,3,0,1],[1,5,-3,8],[12,5,7,0],[6,77,15,35]])
b1=np.array([[1],[2],[3]])
b2=np.array([[-1],[0],[1],[2]])

In [3]:
U1,S1,V1t=np.linalg.svd(A1)
U2,S2,V2t=np.linalg.svd(A2)

x1=V1t.T@(np.diag(1/S1))@U1.T@b1
x2=V2t.T@(np.diag(1/S2))@U2.T@b2

print('result of first system using SVD is:\n',x1)
print('result of second system using SVD is:\n',x2)

print('result of first system using ordinary operation:\n',np.linalg.inv(A1)@b1)
print('result of second system using ordinary operation:\n',np.linalg.inv(A2)@b2)

result of first system using SVD is:
 [[ 0.33333333]
 [-0.66666667]
 [ 2.        ]]
result of second system using SVD is:
 [[-0.30724005]
 [-0.46615152]
 [ 1.00251974]
 [ 0.70569461]]
result of first system using ordinary operation:
 [[ 0.33333333]
 [-0.66666667]
 [ 2.        ]]
result of second system using ordinary operation:
 [[-0.30724005]
 [-0.46615152]
 [ 1.00251974]
 [ 0.70569461]]
