# Problem 1.27
## Finding inverse matrix using row reduced echelon form
We will only use Numpy Library to formulate array structure. Main idea is to implement rref algorithm to below function  
defined as 'elemrowop', 'elemrowop2', and 'diagop'

In [2]:
import numpy as np

A=np.array([[1,3,-1,-9],[0,3,0,1],[12,8,-11,0],[2,1,5,3]])
print(A)
Ainv=np.linalg.inv(A)
print(Ainv)

I=np.diag([1,1,1,1])
print(I)


[[  1   3  -1  -9]
 [  0   3   0   1]
 [ 12   8 -11   0]
 [  2   1   5   3]]
[[ 0.02003339 -0.22287145  0.05926544  0.13439065]
 [ 0.03422371  0.30676127 -0.00292154  0.00041736]
 [ 0.04674457 -0.02003339 -0.02838063  0.14691152]
 [-0.10267112  0.07971619  0.00876461 -0.00125209]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### Function Definition for calculation of inverse matrix

In [18]:
#This function applies for (m,n) matrix. Elementary row op, with initial entries not normalized to 1
def elemrowop(A,I,m,n):
    tempA=A
    tempI=I
    ref=0
    for i in range(0,n):
        if(ref>=m):
            break
        if ((tempA[ref:m,i]==np.zeros((1,m-ref))).all()):
            continue
        for j in range(ref,m):
            if(tempA[j,i]==0):
                continue
            else:
                break
        E1=np.eye(m,k=0,dtype=float)
        if(ref!=j):
            E1[ref,ref]=0;E1[j,j]=0;E1[ref,j]=1;E1[j,ref]=1
        tempA=E1@tempA
        tempI=E1@tempI
        E2=np.eye(m,k=0,dtype=float)
        for j in range(ref+1,m):
            E2[j,ref]=-((tempA[j,i])/(tempA[ref,i]))
        tempA=E2@tempA
        tempI=E2@tempI
        ref+=1
    return tempA,tempI

#This function only applies to square matrix
def elemrowop2(A,I,n):
    tempA=A
    tempI=I
    if((np.diag(A)==np.zeros((1,n))).any()):
        print('A is singular matrix')
        return 0,0
    else:
        for i in range(0,n):
            E=np.eye(n,k=0,dtype=float)
            for j in range(0,n-i-1):
                E[j,n-1-i]=-tempA[j,n-1-i]/tempA[n-1-i,n-1-i]
            tempA=E@tempA
            tempI=E@tempI
    return tempA,tempI

#Not used in this class, but implemented column operation, just in case for the future
#This function applies for (m,n) matrix. Elementary column op, with initial entries not normalized to 1
def elemcolop(A,I,m,n):
    tempA=A
    tempI=I
    ref=0
    for i in range(0,n):
        if(ref>=n):
            break
        if ((tempA[i,ref:n]==np.zeros((1,n-ref))).all()):
            continue
        for j in range(ref,n):
            if(tempA[i,j]==0):
                continue
            else:
                break
        E1=np.eye(n,k=0,dtype=float)
        if(ref!=j):
            E1[ref,ref]=0;E1[j,j]=0;E1[ref,j]=1;E1[j,ref]=1
        tempA=tempA@E1
        tempI=tempI@E1
        E2=np.eye(n,k=0,dtype=float)
        for j in range(ref+1,n):
            E2[ref,j]=-((tempA[i,j])/(tempA[i,ref]))
        tempA=tempA@E2
        tempI=tempI@E2
        ref+=1
    return tempA,tempI

#This function only applies to square matrix
def diagop(A,I,n):
    tempA=A
    tempI=I
    diag=np.eye(n,k=0,dtype=float)
    for i in range(0,n):
        if(tempA[i,i]==0):
            diag[i,i]=0
        else:
            diag[i,i]=1/tempA[i,i]
    tempA=diag@tempA
    tempI=diag@tempI    
    return tempA,tempI
    


### The result is shown as below.

In [19]:
temp=elemrowop(A,I,4,4)
temp=elemrowop2(temp[0],temp[1],4)
temp=diagop(temp[0],temp[1],4)
print(temp[1])

[[ 0.02003339 -0.22287145  0.05926544  0.13439065]
 [ 0.03422371  0.30676127 -0.00292154  0.00041736]
 [ 0.04674457 -0.02003339 -0.02838063  0.14691152]
 [-0.10267112  0.07971619  0.00876461 -0.00125209]]


### This calculation is double checked by inverse matrix function defined on Numpy library

In [4]:
Ainv=np.linalg.inv(A)
print(Ainv)

[[ 0.02003339 -0.22287145  0.05926544  0.13439065]
 [ 0.03422371  0.30676127 -0.00292154  0.00041736]
 [ 0.04674457 -0.02003339 -0.02838063  0.14691152]
 [-0.10267112  0.07971619  0.00876461 -0.00125209]]
