# Problem 3.21

In [1]:
import numpy as np

A=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
            [13, 14, 15, 16]])
B=np.array([[-1, 1, 2],
            [4, 5, 6],
            [7, 8, 9],
            [10, 11, 12]])

In [2]:
#This function applies for (m,n) matrix. Elementary row op, with initial entries not normalized to 1
def elemrowop(A,m,n):
    tempA=A
    ref=0
    for i in range(0,n):
        if(ref>=m):
            break
        if ((tempA[ref:m,i]==np.zeros((1,m-ref))).all()):
            continue
        for j in range(ref,m):
            if(tempA[j,i]==0):
                continue
            else:
                break
        E1=np.eye(m,k=0,dtype=float)
        if(ref!=j):
            E1[ref,ref]=0;E1[j,j]=0;E1[ref,j]=1;E1[j,ref]=1
        tempA=E1@tempA
        E2=np.eye(m,k=0,dtype=float)
        for j in range(ref+1,m):
            E2[j,ref]=-((tempA[j,i])/(tempA[ref,i]))
        tempA=E2@tempA
        ref+=1
    return tempA

#Function for rank of (m,n) matrix
def rank(A,m,n):
    tempA=A
    rankA=0
    for i in range(0,m):
        for j in range(0,n):
            if(abs(tempA[i,j])<=1e-10):tempA[i,j]=0
    if(m>=n):
        for i in range(0,m):
            if((tempA[i,:]!=np.zeros((1,n),dtype=float)).any()):
                rankA+=1
    else:
        for j in range(0,n):
            if((tempA[:,j]!=np.zeros((1,m),dtype=float)).any()):
                rankA+=1
    return rankA
        




## (a)

In [3]:
elemrowopA=elemrowop(A,4,4)
print(elemrowopA)
elemrowopB=elemrowop(B,4,3)
print(elemrowopB)

[[  1.   2.   3.   4.]
 [  0.  -4.  -8. -12.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[-1.          1.          2.        ]
 [ 0.          9.         14.        ]
 [ 0.          0.         -0.33333333]
 [ 0.          0.          0.        ]]


In [4]:
rkA=rank(elemrowopA,4,4)
rkB=rank(elemrowopB,4,3)
print('rank of matrix A is %d'%(rkA))
print('rank of matrix B is %d'%(rkB))

rank of matrix A is 2
rank of matrix B is 3


## (b)

In [5]:
AtA=np.transpose(A)@A
BtB=np.transpose(B)@B
temp1=elemrowop(AtA,4,4)
temp2=elemrowop(BtB,3,3)
rkAtA=rank(temp1,4,4)
rkBtB=rank(temp2,3,3)
print('rank of matrix AtA is %d'%(rkAtA))
print('rank of matrix BtB is %d'%(rkBtB))

rank of matrix AtA is 2
rank of matrix BtB is 3
