# Problem 4.30

## a. Calculating the determinant of Hilbert Matrix
Calculation is conducted in 3 methods. First, I implemented **self-made determinant calculating function named 'determinant'**  
using method of elementary row operation.

Second, **sympy library is used to calcuate the H5, H10, H15, and H25.** In sympy library, det() function, which calculates  
determinant of symH5, symH10 symH15, and symH20(Hilbert matrix defined using sympy library, defined on below codes) in a  
exact way. But because sympy library is quite slow in conducting operation, H25 was excluded in this procedure.  

##### First, import python libraries useful in this calculation

In [16]:
import numpy as np
from sympy import Matrix,pprint

#### Second, define elementary row operation function and determinant function based on elementary row operaton.  
Elementary row operation in this function does not include normalization of 1st non-zero entries of each row.

In [17]:
#This function applies for (m,n) matrix. Elementary row op, with initial entries not normalized to 1
def elemrowop(A,I,m,n):
    tempA=A
    tempI=I
    ref=0
    for i in range(0,n):
        if(ref>=m):
            break
        if ((tempA[ref:m,i]==np.zeros((1,m-ref))).all()):
            continue
        for j in range(ref,m):
            if(tempA[j,i]==0):
                continue
            else:
                break
        E1=np.eye(m,k=0,dtype=float)
        if(ref!=j):
            E1[ref,ref]=0;E1[j,j]=0;E1[ref,j]=1;E1[j,ref]=1
        tempA=E1@tempA
        tempI=E1@tempI
        E2=np.eye(m,k=0,dtype=float)
        for j in range(ref+1,m):
            E2[j,ref]=-((tempA[j,i])/(tempA[ref,i]))
        tempA=E2@tempA
        tempI=E2@tempI
        ref+=1
    return tempA,tempI

#This function only applies to square matrix
def elemrowop2(A,I,n):
    tempA=A
    tempI=I
    if((np.diag(A)==np.zeros((1,n))).any()):
        print('A is singular matrix')
        return 0,0
    else:
        for i in range(0,n):
            E=np.eye(n,k=0,dtype=float)
            for j in range(0,n-i-1):
                E[j,n-1-i]=-tempA[j,n-1-i]/tempA[n-1-i,n-1-i]
            tempA=E@tempA
            tempI=E@tempI
    return tempA,tempI

#This function only applies to square matrix
def diagop(A,I,n):
    tempA=A
    tempI=I
    diag=np.eye(n,k=0,dtype=float)
    for i in range(0,n):
        if(tempA[i,i]==0):
            diag[i,i]=0
        else:
            diag[i,i]=1/tempA[i,i]
    tempA=diag@tempA
    tempI=diag@tempI    
    return tempA,tempI

#Function for determinant of a matrix
def determinant(A,n):
    tempA=A
    ref=0
    sgn=0
    det=1
    for i in range(0,n):
        if(ref>=n):
            break
        if ((tempA[ref:n,i]==np.zeros((1,n-ref))).all()):
            continue
        for j in range(ref,n):
            if(tempA[j,i]==0):
                continue
            else:
                break
        E1=np.eye(n,k=0,dtype=float)
        if(ref!=j):
            E1[ref,ref]=0;E1[j,j]=0;E1[ref,j]=1;E1[j,ref]=1
            sgn+=1
        tempA=E1@tempA
        E2=np.eye(n,k=0,dtype=float)
        for j in range(ref+1,n):
            E2[j,ref]=-((tempA[j,i])/(tempA[ref,i]))
        tempA=E2@tempA
        ref+=1
    
    #diagonal product
    for i in range(0,n):
        det*=tempA[i,i]
    det=det*pow(-1,sgn)
    
    return det

def hilbert(n):
    A=np.zeros((n,n))
    for i in range(0,n):
        for j in range(0,n):
            A[i,j]=1/(i+j+1)
    return A

### Third, calculate determinant of Hilbert matrix of n=5,10,15,25 using functions defined above

### Below code is answer for (a)

In [18]:
H5=hilbert(5)
H10=hilbert(10)
H15=hilbert(15)
H25=hilbert(25)

#detH5=determinant(H5,5)
#detH10=determinant(H10,10)
#detH15=determinant(H15,15)
#detH25=determinant(H25,25)

detH5=Matrix(H5).det()
detH10=Matrix(H10).det()
detH15=Matrix(H15).det()
detH25=Matrix(H25).det()

print('determinant of hilbert matrix of n=5 is %E'%(detH5))
print('determinant of hilbert matrix of n=10 is %E'%(detH10))
print('determinant of hilbert matrix of n=15 is %E'%(detH15))
print('determinant of hilbert matrix of n=25 is %E'%(detH25))

print('\nAs n gets bigger, elements in the inverse matrix tends to get smaller toward 0')

determinant of hilbert matrix of n=5 is 3.749295E-12
determinant of hilbert matrix of n=10 is 2.164327E-53
determinant of hilbert matrix of n=15 is -6.011556E-121
determinant of hilbert matrix of n=25 is 1.371693E-273

As n gets bigger, elements in the inverse matrix tends to get smaller toward 0


### Fourth, define Hilbert matrix H5 using sympy library. Then, compute the inverse of H5 using sympy algorithm or RREF defined above.

### Below code is answer for (b)

In [19]:
symH5=Matrix(5,5,lambda i,j:1/(i+j+1))
invH5=symH5.inv('GE')
pprint(invH5)

temp=elemrowop(H5,np.eye(5,5,dtype=float),5,5)
temp=elemrowop2(temp[0],temp[1],5)
temp=diagop(temp[0],temp[1],5)
print(temp[1])

⎡ 25     -300    1050     -1400    630  ⎤
⎢                                       ⎥
⎢-300    4800   -18900    26880   -12600⎥
⎢                                       ⎥
⎢1050   -18900   79380   -117600  56700 ⎥
⎢                                       ⎥
⎢-1400  26880   -117600  179200   -88200⎥
⎢                                       ⎥
⎣ 630   -12600   56700   -88200   44100 ⎦
[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]


### (c) From this part, huge amount of calculation will be continued, for H20 is contained in the exercise. Sympy library can calculate inverse Hilbert matrix up to n=15. For n=25, calcualtion takes too much time.
### Below cases are inverse matrix calculated from RREF functions defined above.

In [20]:
temp=elemrowop(H5,np.eye(5,5,dtype=float),5,5)
temp=elemrowop2(temp[0],temp[1],5)
temp=diagop(temp[0],temp[1],5)
invH5=temp[1]
print('inverse of Hilbert matrix with n=5 is =')
print(invH5)

temp=elemrowop(H10,np.eye(10,10,dtype=float),10,19)
temp=elemrowop2(temp[0],temp[1],10)
temp=diagop(temp[0],temp[1],10)
invH10=temp[1]
print('inverse of Hilbert matrix with n=10 is =')
print(invH10)

temp=elemrowop(H15,np.eye(15,15,dtype=float),15,15)
temp=elemrowop2(temp[0],temp[1],15)
temp=diagop(temp[0],temp[1],15)
invH15=temp[1]
print('inverse of Hilbert matrix with n=15 is =')
print(invH15)

temp=elemrowop(H25,np.eye(25,25,dtype=float),25,25)
temp=elemrowop2(temp[0],temp[1],25)
temp=diagop(temp[0],temp[1],25)
invH25=temp[1]
print('inverse of Hilbert matrix with n=25 is =')
print(invH25)

inverse of Hilbert matrix with n=5 is =
[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]
inverse of Hilbert matrix with n=10 is =
[[ 9.99963464e+01 -4.94968265e+03  7.91932146e+04 -6.00538134e+05
   2.52222425e+06 -6.30548552e+06  9.60826173e+06 -8.75030517e+06
   4.37511954e+06 -9.23630230e+05]
 [-4.94968279e+03  3.26672458e+05 -5.88001128e+06  4.75621536e+07
  -2.08082250e+08  5.35063973e+08 -8.32315569e+08  7.70028547e+08
  -3.89824795e+08  8.31272183e+07]
 [ 7.91932195e+04 -5.88001144e+06  1.12894942e+08 -9.51235769e+08
   4.28052898e+09 -1.12363183e+10  1.77560631e+10 -1.66326445e+10
   8.50529585e+09 -1.82880725e+09]
 [-6.00538191e+05  4.75621561e+07 -9.51235790e+08  8.24399242e+09
  -3.78706472e+10  1.00987962e+11 -1.61580154e+11  1.52886126

### For Sympy case, H5, H10, H15 cases are only calculated.

In [21]:
symH5=Matrix(5,5,lambda i,j:1/(i+j+1))
syminvH5=symH5.inv('GE')
pprint(syminvH5)

symH10=Matrix(10,10,lambda i,j:1/(i+j+1))
syminvH10=symH10.inv('GE')
pprint(syminvH10)

symH15=Matrix(15,15,lambda i,j:1/(i+j+1))
syminvH15=symH15.inv('GE')
pprint(syminvH15)

'''
symH25=Matrix(25,25,lambda i,j:1/(i+j+1))
syminvH25=symH25.inv('GE')
pprint(syminvH25)
'''

⎡ 25     -300    1050     -1400    630  ⎤
⎢                                       ⎥
⎢-300    4800   -18900    26880   -12600⎥
⎢                                       ⎥
⎢1050   -18900   79380   -117600  56700 ⎥
⎢                                       ⎥
⎢-1400  26880   -117600  179200   -88200⎥
⎢                                       ⎥
⎣ 630   -12600   56700   -88200   44100 ⎦
⎡  100       -4950        79200         -600600        2522520        -6306300
⎢                                                                             
⎢ -4950      326700      -5880600      47567520      -208107900      535134600
⎢                                                                             
⎢ 79200     -5880600    112907520     -951350400     4281076800     -112378266
⎢                                                                             
⎢-600600    47567520    -951350400    8245036800    -37875637800    1010017008
⎢                                                                    

"\nsymH25=Matrix(25,25,lambda i,j:1/(i+j+1))\nsyminvH25=symH25.inv('GE')\npprint(syminvH25)\n"

### Inverse matrix calculated from RREF function, and determinant calculated by RREF algorithm

In [26]:
detinvH5=determinant(invH5,5)
detinvH10=determinant(invH10,10)
detinvH15=determinant(invH15,15)
detinvH25=determinant(invH25,25)

print('determinant of inverse hilbert matrix of n=5 is %E'%(detinvH5))
print('determinant of inverse hilbert matrix of n=10 is %E'%(detinvH10))
print('determinant of inverse hilbert matrix of n=15 is %E'%(detinvH15))
print('determinant of inverse hilbert matrix of n=25 is %E'%(detinvH25))

determinant of inverse hilbert matrix of n=5 is 2.667168E+11
determinant of inverse hilbert matrix of n=10 is 4.620250E+52
determinant of inverse hilbert matrix of n=15 is 8.178397E+120
determinant of inverse hilbert matrix of n=25 is 1.822997E+278


In [27]:
#Determinant comparison, using row operation function defined on this code
assumpH5=detH5*detinvH5
assumpH10=detH10*detinvH10
assumpH15=detH15*detinvH15
assumpH25=detH25*detinvH25

print('det(H5)*det(invH5) is %E'%(assumpH5))
print('det(H10)*det(invH10) is %E'%(assumpH10))
print('det(H15)*det(invH15) is %E'%(assumpH15))
print('det(H25)*det(invH25) is %E'%(assumpH25))
print('\nBecause of float error, inverse relation does not solves for n=10,15,25.')
print('At MATLAB, floating error also occurs during calculation, but is smaller than the ones calculated in')
print('this code, in a order of 1. I am not sure how the det function in MATLAB is designed, but it is sure that')
print('some improvements are required to solve this inaccuracy.')

det(H5)*det(invH5) is 1.000000E+00
det(H10)*det(invH10) is 9.999730E-01
det(H15)*det(invH15) is -4.916490E+00
det(H25)*det(invH25) is 2.500591E+05

Because of float error, inverse relation does not solves for n=10,15,25.
At MATLAB, floating error also occurs during calculation, but is smaller than the ones calculated in
this code, in a order of 1. I am not sure how the det function in MATLAB is designed, but it is sure that
some improvements are required to solve this inaccuracy.


### As expected, inverse relation is well shown at sympy calculation

In [10]:
#determinant comparison, using sympy library
symassumpH5=symH5.det()*syminvH5.det()
symassumpH10=symH10.det()*syminvH10.det()
symassumpH15=symH15.det()*syminvH15.det()
#symassumpH25=detH25.det()*detinvH25.det()

print('det(symH5)*det(syminvH5) is %E'%(symassumpH5))
print('det(symH10)*det(syminvH10) is %E'%(symassumpH10))
print('det(symH15)*det(syminvH15) is %E'%(symassumpH15))
#print('det(symH25)*det(syminvH25) is %E'%(symassumpH25))

det(symH5)*det(syminvH5) is 1.000000E+00
det(symH10)*det(syminvH10) is 1.000000E+00
det(symH15)*det(syminvH15) is 1.000000E+00


### But Sympy library cannot handle high order system such as n=25. To solve this limitation, we implement inverse using RREF, and calculate determinant using sympy library.

In [28]:
detinvH5=Matrix(invH5).det()
detinvH10=Matrix(invH10).det()
detinvH15=Matrix(invH15).det()
detinvH25=Matrix(invH25).det()

print('determinant of inverse hilbert matrix of n=5 is %E'%(detinvH5))
print('determinant of inverse hilbert matrix of n=10 is %E'%(detinvH10))
print('determinant of inverse hilbert matrix of n=15 is %E'%(detinvH15))
print('determinant of inverse hilbert matrix of n=25 is %E'%(detinvH25))

determinant of inverse hilbert matrix of n=5 is 2.667168E+11
determinant of inverse hilbert matrix of n=10 is 4.620037E+52
determinant of inverse hilbert matrix of n=15 is 1.042162E+120
determinant of inverse hilbert matrix of n=25 is -9.897641E+274


In [29]:
#Determinant comparison, using row operation function defined on this code
assumpH5=detH5*detinvH5
assumpH10=detH10*detinvH10
assumpH15=detH15*detinvH15
assumpH25=detH25*detinvH25

print('det(H5)*det(invH5) is %E'%(assumpH5))
print('det(H10)*det(invH10) is %E'%(assumpH10))
print('det(H15)*det(invH15) is %E'%(assumpH15))
print('det(H25)*det(invH25) is %E'%(assumpH25))

print('\nError is reduced compared with the first case')

det(H5)*det(invH5) is 1.000000E+00
det(H10)*det(invH10) is 9.999269E-01
det(H15)*det(invH15) is -6.265017E-01
det(H25)*det(invH25) is -1.357652E+02

Error is reduced compared with the first case
