In [1]:
import numpy as np

In [26]:
def ARNOLDI(A,x1,m):
    n=np.shape(A)[0]
    Q=np.zeros((n,m+1))
    H=np.zeros((m+1,m))
    Q[:,0]=x1/np.linalg.norm(x1,2)
    for i in range(0,m):
        w=A@Q[:,i]
        for j in range(0,i+1):
            H[j,i]=np.dot(Q[:,j],w)
            w=w-H[j,i]*Q[:,j]
        H[i+1,i]=np.linalg.norm(w,2)
        if H[i+1,i]==0:return Q,H
        Q[:,i+1]=w/H[i+1,i]
    return Q,H


def LANCZOS(A,x0,m):
    n=np.shape(A)[0]
    Q=np.zeros([n,m+2])
    T=np.zeros([m+1,m])
    alpha=np.zeros([m,1])
    beta=np.zeros([m+1,1])
    Q[:,0]=0;beta[0,0]=0;Q[:,1]=x0/np.linalg.norm(x0,2)
    for i in range(1,m+1):
        w=A@Q[:,i]
        alpha[i-1,0]=np.dot(Q[:,i],w)
        w=w-beta[i-1,0]*Q[:,i-1]-alpha[i-1,0]*Q[:,i]
        beta[i,0]=np.linalg.norm(w,2)
        Q[:,i+1]=w/beta[i,0]
    T[0:m,0:m]=np.diag(alpha[0:m,0])+np.diag(beta[1:m,0],-1)+np.diag(beta[1:m,0],1)
    T[m,m-1]=beta[m,0]
    return Q[:,1:m+2],T

In [3]:
#21.18
A=np.array([[1,3,-1,7,2],[5,-8,25,3,12],[0,-1,0,3,7],[8,-3,23,6,9],[56,13,8,-9,1]])
x1=np.transpose(np.random.rand(5,1))
Q,H=ARNOLDI(A,x1,3)

print('The Q matrix is:\n',Q)
print('\nThe H matrix is:\n',H)
print('\nnorm(A*Q(:,1:m) - Q*H) is: ',np.linalg.norm(A@Q[:,0:3]-Q@H,2))

The Q matrix is:
 [[ 0.12048176  0.20098979  0.4536044  -0.65580897]
 [ 0.25896678  0.79540125 -0.09903044  0.46041133]
 [ 0.48776714 -0.48249486 -0.43911773  0.11934532]
 [ 0.67117729  0.18342363 -0.24507517 -0.43079267]
 [ 0.47960883 -0.24595615  0.72907462  0.39763095]]

The H matrix is:
 [[ 25.32372653  -6.74853603  12.80623559]
 [ 15.00586895 -20.31927926  -7.99857976]
 [  0.          19.30930272  15.6072433 ]
 [  0.           0.          10.18062525]]

norm(A*Q(:,1:m) - Q*H) is:  5.415959340695319e-15


In [39]:
#21.19
A=np.array([[1,5,3,-1,6],[5,1,7,-8,2],[3,7,12,-1,3],[-1,-8,-1,9,4],[6,2,3,4,1]])
x0=np.transpose(np.random.rand(5,1))
Q,T=LANCZOS(A,x0,3)

print('The Q matrix is:\n',Q)
print('\nThe T matrix is:\n',T)
print('\nnorm(A*Q(:,1:m) - Q*T) is: ',np.linalg.norm(A@Q[:,0:3]-Q@T,2))

The Q matrix is:
 [[ 0.13916332  0.59482315 -0.20281537 -0.47097286]
 [ 0.02786637  0.75468628 -0.13362446  0.27833552]
 [ 0.80811865  0.03834268  0.32117339  0.43761606]
 [ 0.39070522 -0.26326383 -0.87378587  0.00492107]
 [ 0.41731368 -0.07652472  0.27268358 -0.71356981]]

The T matrix is:
 [[13.59043456  4.91698755  0.        ]
 [ 4.91698755  9.48025636 10.03840167]
 [ 0.         10.03840167  3.67066105]
 [ 0.          0.          5.571738  ]]

norm(A*Q(:,1:m) - Q*T) is:  2.210223101981737e-15
