In [1]:
import numpy as np

In [3]:
def cholesky(A):
    n=np.shape(A)[0]
    R=np.zeros([n,n])
    for i in range(0,n):
        for j in range(i,n):
            if(i>j):
                R[i,j]=0
            elif(i==j):
                if(i==0):
                    if A[i,j]<0:
                        print("Error: A is not positive definite")
                        return
                    R[i,j]=np.sqrt(A[i,j])
                else:
                    if A[i,j]-np.sum(R[0:i,i]**2)<0:
                        print("Error: A is not positive definite")
                        return
                    R[i,j]=np.sqrt(A[i,j]-np.sum(R[0:i,i]**2))
            else:
                R[i,j]=(A[i,j]-np.sum(R[0:i,i]*R[0:i,j]))/R[i,i]
    return R,R.transpose()

In [6]:
A=np.array([[0.2090, 0.0488, -0.0642, -0.0219],
            [0.0488, 0.1859, -0.0921, -0.0475],
            [-0.0642, -0.0921, 0.4257, 0.0364],
            [-0.0219, -0.0475, 0.0364, 0.1973]])

R,Rt=cholesky(A)
print(R)
print(np.linalg.norm(A-Rt@R))

[[ 0.45716518  0.10674479 -0.14043064 -0.04790391]
 [ 0.          0.41773861 -0.18458854 -0.10146658]
 [ 0.          0.          0.60984121  0.01794443]
 [ 0.          0.          0.          0.42940394]]
7.076311083754595e-17
