In [9]:
import numpy as np
import scipy as sp

In [15]:
def QRdecomposition(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for i in range(0,n):
        v=A[:,i]
        Q[:,i]=v
        for j in range(0,i):
            Q[:,i]-=np.dot(v,Q[:,j])*Q[:,j]
            R[j,i]=np.dot(v,Q[:,j])
        R[i,i]=np.linalg.norm(Q[:,i])
        Q[:,i]=Q[:,i]/np.linalg.norm(Q[:,i])
        
    return Q,R

In [21]:
A1=np.array([[1, -1,  3, 4],
             [2,  1,  4, 9],
             [0,  3,  2, 5],
             [1,  5, -1, 6],
             [4, -8,  6, 6]])

A2=np.array([[1,   8,  -1,  3,  2],
             [5,   7,  -9,  1,  4],
             [13, 71, -17, 25, 20]])

Q1,R1=QRdecomposition(A1)
Q2,R2=QRdecomposition(A2)

print('Q1=\n',Q1);print('R1=\n',R1)
print('Q2=\n',Q2);print('R2=\n',R2)
print('Q1.t@Q1=\n',Q1.transpose()@Q1)
print('Q2.t@Q2=\n',Q2.transpose()@Q2)

Q1=
 [[ 0.21320072  0.02184521  0.40818972 -0.28528389]
 [ 0.42640143  0.40413633  0.33092524 -0.08150968]
 [ 0.          0.36044592  0.62540497 -0.4890581 ]
 [ 0.21320072  0.74273704 -0.56271869  0.81509684]
 [ 0.85280287 -0.39321373 -0.12683038  0.09169839]]
R1=
 [[ 4.69041576e+00 -5.54321863e+00  7.24882436e+00  1.10864373e+01]
 [ 0.00000000e+00  8.32302393e+00 -6.99046629e-01  7.62397730e+00]
 [ 0.00000000e+00  0.00000000e+00  3.60081647e+00  3.60081647e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  5.44830001e-15]]


In [20]:
Q1_rev,R1_rev=sp.linalg.qr(A1,mode='economic')
Q2_rev,R2_rev=sp.linalg.qr(A2,mode='economic')

print(Q1_rev);print(R1_rev)
print(Q2_rev);print(R2_rev)

print(Q1_rev.transpose()@Q1_rev)
print(Q2_rev.transpose()@Q2_rev)

[[-0.21320072 -0.02184521 -0.40818972 -0.8606548 ]
 [-0.42640143 -0.40413633 -0.33092524  0.42458468]
 [-0.         -0.36044592 -0.62540497  0.13530749]
 [-0.21320072 -0.74273704  0.56271869 -0.23831301]
 [-0.85280287  0.39321373  0.12683038  0.06244961]]
[[-4.69041576e+00  5.54321863e+00 -7.24882436e+00 -1.10864373e+01]
 [ 0.00000000e+00 -8.32302393e+00  6.99046629e-01 -7.62397730e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.60081647e+00 -3.60081647e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.79018084e-15]]
